CREATE DATABASE IF NOT EXISTS career_coach;
USE career_coach;

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    coach_name VARCHAR(255),
    coach_email VARCHAR(255),
    status VARCHAR(50) NOT NULL, -- PENDING, BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW
    start_time DATETIME,
    end_time DATETIME,
    cal_booking_uid VARCHAR(255),
    cal_booking_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
